# Generated by Django 4.2.7 on 2025-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='prioridad',
            field=models.IntegerField(default=0, help_text='Nivel de prioridad del usuario (para upgrades, etc.)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del usuario', max_length=15, null=True),
        ),
    ]
