# Generated by Django 4.2.7 on 2025-06-18 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=10, unique=True)),
                ('codigo_icao', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_total', models.IntegerField()),
                ('filas_total', models.IntegerField()),
                ('asientos_por_fila', models.IntegerField()),
                ('tiene_primera_clase', models.BooleanField(default=False)),
                ('tiene_clase_ejecutiva', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=20)),
                ('flight_date', models.DateField()),
                ('flight_status', models.CharField(max_length=50)),
                ('fecha_salida_programada', models.DateTimeField()),
                ('fecha_llegada_programada', models.DateTimeField()),
                ('fecha_salida_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('terminal_salida', models.CharField(blank=True, max_length=20)),
                ('gate_salida', models.CharField(blank=True, max_length=10)),
                ('terminal_llegada', models.CharField(blank=True, max_length=20)),
                ('gate_llegada', models.CharField(blank=True, max_length=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asientos_disponibles', models.IntegerField()),
                ('duracion_minutos', models.IntegerField()),
                ('api_flight_iata', models.CharField(max_length=20)),
                ('api_flight_icao', models.CharField(max_length=20)),
                ('codeshare_info', models.CharField(blank=True, max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.aerolinea')),
                ('aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegadas', to='vuelos.aeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='vuelos.aeropuerto')),
                ('modelo_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.modeloavion')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=5)),
                ('fila', models.IntegerField()),
                ('columna', models.CharField(max_length=1)),
                ('clase', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.vuelo')),
            ],
        ),
    ]
