# Generated by Django 5.2.2 on 2025-07-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='codigo_icao',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
