# Generated by Django 5.2.2 on 2025-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_alter_aeropuerto_codigo_icao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='codigo_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
