# Generated by Django 4.2.7 on 2025-07-06 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vuelos', '0003_alter_aeropuerto_codigo_iata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_reservados', to=settings.AUTH_USER_MODEL),
        ),
    ]
